/**
 * TEAM: frontend_infra
 *
 * @flow strict
 */

/**
 * Provides common contants for CRUD operations
 */
export const ActionTypes = {
  CREATE: "CREATE",
  PROCESS_SUCCESSFUL_CREATE: "PROCESS_SUCCESSFUL_CREATE",
  READ: "READ",
  PROCESS_SUCCESSFUL_READ: "PROCESS_SUCCESSFUL_READ",
  UPDATE: "UPDATE",
  PROCESS_SUCCESSFUL_UPDATE: "PROCESS_SUCCESSFUL_UPDATE",
  UPDATE_COLLECTION: "UPDATE_COLLECTION",
  DESTROY: "DESTROY",
  PROCESS_SUCCESSFUL_DESTROY: "PROCESS_SUCCESSFUL_DESTROY",
};

export const EventTypes = {
  CREATING: "CREATING",
  CREATE_SUCCESS: "CREATE_SUCCESS",
  CREATE_ERROR: "CREATE_ERROR",

  READING: "READING",
  READ_SUCCESS: "READ_SUCCESS",
  READ_ERROR: "READ_ERROR",

  UPDATING: "UPDATING",
  UPDATE_SUCCESS: "UPDATE_SUCCESS",
  UPDATE_ERROR: "UPDATE_ERROR",

  UPDATING_COLLECTION: "UPDATING_COLLECTION",
  UPDATE_COLLECTION_SUCCESS: "UPDATE_COLLECTION_SUCCESS",
  UPDATE_COLLECTION_ERROR: "UPDATE_COLLECTION_ERROR",

  DESTROYING: "DESTROYING",
  DESTROY_SUCCESS: "DESTROY_SUCCESS",
  DESTROY_ERROR: "DESTROY_ERROR",
};
