// flow-typed signature: 24e215461bba894d656c910816c48b62
// flow-typed version: <<STUB>>/math-expression-evaluator_v^1.2.8/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'math-expression-evaluator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'math-expression-evaluator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'math-expression-evaluator/dist/browser/math-expression-evaluator' {
  declare module.exports: any;
}

declare module 'math-expression-evaluator/dist/browser/math-expression-evaluator.min' {
  declare module.exports: any;
}

declare module 'math-expression-evaluator/src/formula_evaluator' {
  declare module.exports: any;
}

declare module 'math-expression-evaluator/src/lexer' {
  declare module.exports: any;
}

declare module 'math-expression-evaluator/src/math_function' {
  declare module.exports: any;
}

declare module 'math-expression-evaluator/src/postfix_evaluator' {
  declare module.exports: any;
}

declare module 'math-expression-evaluator/src/postfix' {
  declare module.exports: any;
}

declare module 'math-expression-evaluator/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'math-expression-evaluator/dist/browser/math-expression-evaluator.js' {
  declare module.exports: $Exports<'math-expression-evaluator/dist/browser/math-expression-evaluator'>;
}
declare module 'math-expression-evaluator/dist/browser/math-expression-evaluator.min.js' {
  declare module.exports: $Exports<'math-expression-evaluator/dist/browser/math-expression-evaluator.min'>;
}
declare module 'math-expression-evaluator/src/formula_evaluator.js' {
  declare module.exports: $Exports<'math-expression-evaluator/src/formula_evaluator'>;
}
declare module 'math-expression-evaluator/src/lexer.js' {
  declare module.exports: $Exports<'math-expression-evaluator/src/lexer'>;
}
declare module 'math-expression-evaluator/src/math_function.js' {
  declare module.exports: $Exports<'math-expression-evaluator/src/math_function'>;
}
declare module 'math-expression-evaluator/src/postfix_evaluator.js' {
  declare module.exports: $Exports<'math-expression-evaluator/src/postfix_evaluator'>;
}
declare module 'math-expression-evaluator/src/postfix.js' {
  declare module.exports: $Exports<'math-expression-evaluator/src/postfix'>;
}
declare module 'math-expression-evaluator/test/index.js' {
  declare module.exports: $Exports<'math-expression-evaluator/test/index'>;
}
