// flow-typed signature: 63a2768090568b1b55fbfd3b9c34841b
// flow-typed version: <<STUB>>/scrollparent_v0.1.x/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scrollparent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'scrollparent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scrollparent/scrollparent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scrollparent/scrollparent.js' {
  declare module.exports: $Exports<'scrollparent/scrollparent'>;
}
